-- PE source-system v2 reporting schema.
-- Safe fallback DDL for MySQL. Prefer `python manage.py migrate pe_migration`
-- when Django migrations can be applied.

START TRANSACTION;

CREATE TABLE IF NOT EXISTS `source_migration_batch_v2` (
  `migration_batch_id` varchar(64) NOT NULL,
  `system_name` varchar(40) NOT NULL DEFAULT 'pe',
  `database_name` varchar(100) NOT NULL,
  `started_at` datetime(6) NOT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `status` varchar(30) NOT NULL,
  `input_file_names` longtext NOT NULL,
  `created_by` varchar(120) NOT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`migration_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `migration_exception_v2` (
  `exception_id` bigint NOT NULL AUTO_INCREMENT,
  `migration_batch_id` varchar(64) NOT NULL,
  `system_name` varchar(40) NOT NULL DEFAULT 'pe',
  `database_name` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `entity_type` varchar(40) NOT NULL,
  `issue_code` varchar(80) NOT NULL,
  `issue_details` longtext NOT NULL,
  `raw_payload_json` longtext NOT NULL,
  `resolution_status` varchar(30) NOT NULL DEFAULT 'open',
  `resolved_by` varchar(120) DEFAULT NULL,
  `resolved_at` datetime(6) DEFAULT NULL,
  `resolution_notes` longtext DEFAULT NULL,
  PRIMARY KEY (`exception_id`),
  KEY `mig_exc_batch_issue_idx` (`migration_batch_id`, `issue_code`),
  KEY `mig_exc_source_idx` (`source_table`, `source_pk_value`),
  KEY `mig_exc_resolution_idx` (`resolution_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_master_identity_cache_v2` (
  `cache_id` varchar(64) NOT NULL,
  `entity_type` varchar(40) NOT NULL,
  `entity_uuid` varchar(64) DEFAULT NULL,
  `source_column` varchar(120) NOT NULL,
  `source_value` varchar(255) NOT NULL,
  `source_value_normalized` varchar(255) DEFAULT NULL,
  `cache_loaded_at` datetime(6) NOT NULL,
  `reconciliation_status` varchar(30) NOT NULL,
  `reconciliation_basis` varchar(100) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`cache_id`),
  KEY `pe_master_cache_lookup_idx` (`entity_type`, `source_value_normalized`),
  KEY `pe_master_cache_uuid_idx` (`entity_type`, `entity_uuid`),
  KEY `pe_master_cache_batch_idx` (`migration_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_campaign_v2` (
  `pe_campaign_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `campaign_id` varchar(100) NOT NULL DEFAULT '',
  `new_video_cluster_name` varchar(255) NOT NULL DEFAULT '',
  `selection_json` longtext NOT NULL,
  `doctors_supported` int unsigned NOT NULL DEFAULT 0,
  `banner_small` varchar(500) NOT NULL DEFAULT '',
  `banner_large` varchar(500) NOT NULL DEFAULT '',
  `banner_target_url` varchar(500) NOT NULL DEFAULT '',
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `video_cluster_id` bigint DEFAULT NULL,
  `publisher_sub` varchar(100) NOT NULL DEFAULT '',
  `publisher_username` varchar(150) NOT NULL DEFAULT '',
  `publisher_roles` varchar(255) NOT NULL DEFAULT '',
  `email_registration` longtext NOT NULL,
  `wa_addition` longtext NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `campaign_uuid` varchar(64) DEFAULT NULL,
  `pe_campaign_id_raw` varchar(100) NOT NULL,
  `pe_campaign_id_normalized` varchar(100) NOT NULL,
  `master_campaign_id_normalized` varchar(100) DEFAULT NULL,
  `video_cluster_uuid` varchar(64) DEFAULT NULL,
  `campaign_mapping_status` varchar(30) NOT NULL,
  `campaign_mapping_basis` varchar(100) NOT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`pe_campaign_uuid`),
  KEY `pe_campaign_norm_idx` (`pe_campaign_id_normalized`),
  KEY `pe_campaign_master_norm_idx` (`master_campaign_id_normalized`),
  KEY `pe_campaign_map_status_idx` (`campaign_mapping_status`),
  KEY `pe_campaign_batch_idx` (`migration_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_clinic_v2` (
  `clinic_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `clinic_code` varchar(50) NOT NULL DEFAULT '',
  `display_name` varchar(255) NOT NULL DEFAULT '',
  `clinic_phone` varchar(30) NOT NULL DEFAULT '',
  `clinic_whatsapp_number` varchar(30) DEFAULT NULL,
  `address_text` longtext NOT NULL,
  `postal_code` varchar(20) NOT NULL DEFAULT '',
  `state` varchar(64) NOT NULL DEFAULT '',
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `clinic_phone_normalized` varchar(20) DEFAULT NULL,
  `clinic_whatsapp_normalized` varchar(20) DEFAULT NULL,
  `global_clinic_uuid` varchar(64) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`clinic_uuid`),
  KEY `pe_clinic_code_idx` (`clinic_code`),
  KEY `pe_clinic_phone_idx` (`clinic_phone_normalized`),
  KEY `pe_clinic_whatsapp_idx` (`clinic_whatsapp_normalized`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_doctor_v2` (
  `pe_doctor_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `doctor_id` varchar(32) NOT NULL DEFAULT '',
  `whatsapp_number` varchar(30) NOT NULL DEFAULT '',
  `imc_number` varchar(64) NOT NULL DEFAULT '',
  `postal_code` varchar(20) DEFAULT NULL,
  `photo` varchar(500) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `clinic_id` bigint DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `doctor_uuid` varchar(64) DEFAULT NULL,
  `clinic_uuid` varchar(64) DEFAULT NULL,
  `doctor_id_raw` varchar(32) NOT NULL DEFAULT '',
  `whatsapp_normalized` varchar(20) DEFAULT NULL,
  `imc_number_normalized` varchar(64) DEFAULT NULL,
  `match_status` varchar(30) NOT NULL,
  `match_basis` varchar(100) NOT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`pe_doctor_uuid`),
  KEY `pe_doctor_raw_id_idx` (`doctor_id_raw`),
  KEY `pe_doctor_phone_idx` (`whatsapp_normalized`),
  KEY `pe_doctor_match_status_idx` (`match_status`),
  KEY `pe_doctor_uuid_idx` (`doctor_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_content_item_v2` (
  `content_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `content_type` varchar(40) NOT NULL,
  `source_code` varchar(100) DEFAULT NULL,
  `source_code_normalized` varchar(100) DEFAULT NULL,
  `display_name_canonical` varchar(255) DEFAULT NULL,
  `parent_content_uuid` varchar(64) DEFAULT NULL,
  `language_code` varchar(10) DEFAULT NULL,
  `is_active_canonical` bool NOT NULL,
  `code` varchar(100) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `description` longtext NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `doctor_trigger_label` varchar(255) DEFAULT NULL,
  `subtopic_title` varchar(255) DEFAULT NULL,
  `navigation_pathways` longtext NOT NULL,
  `search_keywords` longtext NOT NULL,
  `thumbnail_url` varchar(500) DEFAULT NULL,
  `youtube_url` varchar(500) DEFAULT NULL,
  `primary_therapy_id` bigint DEFAULT NULL,
  `primary_trigger_id` bigint DEFAULT NULL,
  `trigger_id` bigint DEFAULT NULL,
  `cluster_id` bigint DEFAULT NULL,
  `video_id` bigint DEFAULT NULL,
  `video_cluster_id` bigint DEFAULT NULL,
  `sort_order` int DEFAULT NULL,
  `is_active` bool DEFAULT NULL,
  `is_published` bool DEFAULT NULL,
  `is_primary` bool DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`content_uuid`),
  UNIQUE KEY `pe_content_type_code_uniq` (`content_type`, `source_code_normalized`),
  KEY `pe_content_lookup_idx` (`content_type`, `source_code_normalized`),
  KEY `pe_content_parent_idx` (`parent_content_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_doctor_share_summary_v2` (
  `doctor_share_summary_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `doctor_id` varchar(32) NOT NULL DEFAULT '',
  `doctor_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `clinic_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `total_shares` bigint unsigned NOT NULL DEFAULT 0,
  `last_shared_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `doctor_uuid` varchar(64) DEFAULT NULL,
  `pe_doctor_uuid` varchar(64) DEFAULT NULL,
  `clinic_uuid` varchar(64) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`doctor_share_summary_uuid`),
  KEY `pe_doc_summary_doctor_idx` (`doctor_uuid`, `pe_doctor_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_share_event_v2` (
  `share_event_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `public_id` varchar(64) NOT NULL DEFAULT '',
  `doctor_summary_id` bigint DEFAULT NULL,
  `doctor_id` varchar(32) NOT NULL DEFAULT '',
  `doctor_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `clinic_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `share_channel` varchar(30) NOT NULL DEFAULT '',
  `shared_by_role` varchar(30) NOT NULL DEFAULT '',
  `shared_item_type` varchar(20) NOT NULL DEFAULT '',
  `shared_item_code` varchar(80) NOT NULL DEFAULT '',
  `shared_item_name` varchar(255) NOT NULL DEFAULT '',
  `language_code` varchar(10) NOT NULL DEFAULT '',
  `recipient_reference` varchar(80) NOT NULL DEFAULT '',
  `recipient_reference_version` smallint unsigned NOT NULL DEFAULT 1,
  `shared_at` datetime(6) DEFAULT NULL,
  `campaign_uuid` varchar(64) DEFAULT NULL,
  `pe_campaign_uuid` varchar(64) DEFAULT NULL,
  `doctor_uuid` varchar(64) DEFAULT NULL,
  `pe_doctor_uuid` varchar(64) DEFAULT NULL,
  `clinic_uuid` varchar(64) DEFAULT NULL,
  `content_uuid` varchar(64) DEFAULT NULL,
  `share_channel_normalized` varchar(30) NOT NULL,
  `share_attribution_type` varchar(40) NOT NULL,
  `actual_shared_by_field_rep_uuid` varchar(64) DEFAULT NULL,
  `assignment_credit_field_rep_uuid` varchar(64) DEFAULT NULL,
  `assignment_credit_basis` varchar(100) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`share_event_uuid`),
  KEY `pe_share_public_id_idx` (`public_id`),
  KEY `pe_share_item_idx` (`shared_item_type`, `shared_item_code`),
  KEY `pe_share_attr_idx` (`share_attribution_type`),
  KEY `pe_share_doctor_idx` (`doctor_uuid`, `pe_doctor_uuid`),
  KEY `pe_share_content_idx` (`content_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_playback_event_v2` (
  `playback_event_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `share_id` bigint DEFAULT NULL,
  `share_public_id` varchar(64) DEFAULT NULL,
  `doctor_summary_id` bigint DEFAULT NULL,
  `doctor_id` varchar(32) NOT NULL DEFAULT '',
  `page_item_type` varchar(20) NOT NULL DEFAULT '',
  `event_type` varchar(20) NOT NULL DEFAULT '',
  `video_code` varchar(80) NOT NULL DEFAULT '',
  `video_name` varchar(255) NOT NULL DEFAULT '',
  `milestone_percent` smallint unsigned DEFAULT NULL,
  `occurred_at` datetime(6) DEFAULT NULL,
  `share_event_uuid` varchar(64) DEFAULT NULL,
  `doctor_uuid` varchar(64) DEFAULT NULL,
  `pe_doctor_uuid` varchar(64) DEFAULT NULL,
  `campaign_uuid` varchar(64) DEFAULT NULL,
  `content_uuid` varchar(64) DEFAULT NULL,
  `assignment_credit_field_rep_uuid` varchar(64) DEFAULT NULL,
  `event_type_normalized` varchar(40) NOT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`playback_event_uuid`),
  KEY `pe_playback_share_idx` (`share_event_uuid`),
  KEY `pe_playback_video_idx` (`video_code`, `event_type_normalized`),
  KEY `pe_playback_content_idx` (`content_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_banner_click_event_v2` (
  `banner_click_event_uuid` varchar(64) NOT NULL,
  `id` bigint DEFAULT NULL,
  `page_type` varchar(20) NOT NULL DEFAULT '',
  `banner_id` varchar(80) NOT NULL DEFAULT '',
  `banner_name` varchar(255) NOT NULL DEFAULT '',
  `banner_target_url` varchar(500) NOT NULL DEFAULT '',
  `clicked_at` datetime(6) DEFAULT NULL,
  `doctor_id` varchar(32) NOT NULL DEFAULT '',
  `doctor_summary_id` bigint DEFAULT NULL,
  `source_banner_click_id` varchar(255) NOT NULL,
  `doctor_uuid` varchar(64) DEFAULT NULL,
  `pe_doctor_uuid` varchar(64) DEFAULT NULL,
  `campaign_uuid` varchar(64) DEFAULT NULL,
  `content_uuid` varchar(64) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`banner_click_event_uuid`),
  KEY `pe_banner_source_idx` (`source_banner_click_id`),
  KEY `pe_banner_campaign_idx` (`campaign_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pe_rep_assignment_credit_v2` (
  `rep_assignment_credit_uuid` varchar(64) NOT NULL,
  `campaign_uuid` varchar(64) NOT NULL,
  `doctor_uuid` varchar(64) NOT NULL,
  `field_rep_uuid` varchar(64) NOT NULL,
  `credit_type` varchar(40) NOT NULL DEFAULT 'assignment_recruitment_credit',
  `credit_source_table` varchar(120) NOT NULL,
  `credit_source_pk` varchar(255) NOT NULL,
  `credit_effective_from` datetime(6) DEFAULT NULL,
  `credit_effective_to` datetime(6) DEFAULT NULL,
  `source_system` varchar(40) NOT NULL,
  `source_database` varchar(100) NOT NULL,
  `source_table` varchar(120) NOT NULL,
  `source_pk_column` varchar(120) NOT NULL,
  `source_pk_value` varchar(255) NOT NULL,
  `source_created_at` datetime(6) DEFAULT NULL,
  `source_updated_at` datetime(6) DEFAULT NULL,
  `migration_batch_id` varchar(64) NOT NULL,
  `migrated_at` datetime(6) NOT NULL,
  `verification_status` varchar(30) NOT NULL,
  `verification_basis` varchar(100) NOT NULL,
  `is_current` bool NOT NULL,
  `valid_from` datetime(6) DEFAULT NULL,
  `valid_to` datetime(6) DEFAULT NULL,
  `raw_payload_json` longtext NOT NULL,
  PRIMARY KEY (`rep_assignment_credit_uuid`),
  KEY `pe_rep_credit_doc_campaign_idx` (`campaign_uuid`, `doctor_uuid`),
  KEY `pe_rep_credit_rep_current_idx` (`field_rep_uuid`, `is_current`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
