# Generated by Django 4.2.29 on 2026-03-18 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorShareSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=32, unique=True)),
                ('doctor_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('clinic_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('total_shares', models.PositiveBigIntegerField(default=0)),
                ('last_shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['doctor_id'],
            },
        ),
        migrations.CreateModel(
            name='ShareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('doctor_id', models.CharField(db_index=True, max_length=32)),
                ('doctor_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('clinic_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('share_channel', models.CharField(default='whatsapp', max_length=30)),
                ('shared_by_role', models.CharField(blank=True, default='', max_length=30)),
                ('shared_item_type', models.CharField(choices=[('video', 'Single video'), ('cluster', 'Video bundle/cluster')], db_index=True, max_length=20)),
                ('shared_item_code', models.CharField(max_length=80)),
                ('shared_item_name', models.CharField(max_length=255)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('recipient_reference', models.CharField(db_index=True, max_length=80)),
                ('recipient_reference_version', models.PositiveSmallIntegerField(default=1)),
                ('shared_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('doctor_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='sharing.doctorsharesummary')),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePlaybackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_public_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('doctor_id', models.CharField(db_index=True, max_length=32)),
                ('page_item_type', models.CharField(choices=[('video', 'Single video'), ('cluster', 'Video bundle/cluster')], max_length=20)),
                ('event_type', models.CharField(choices=[('play', 'Video play'), ('progress', 'View progress milestone')], db_index=True, max_length=20)),
                ('video_code', models.CharField(max_length=80)),
                ('video_name', models.CharField(blank=True, default='', max_length=255)),
                ('milestone_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('doctor_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_events', to='sharing.doctorsharesummary')),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_events', to='sharing.shareactivity')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doctorsharesummary',
            index=models.Index(fields=['last_shared_at'], name='sharing_doc_last_sh_fdbd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shareplaybackevent',
            index=models.Index(fields=['doctor_id', 'occurred_at'], name='sharing_sha_doctor__9dd63b_idx'),
        ),
        migrations.AddIndex(
            model_name='shareplaybackevent',
            index=models.Index(fields=['video_code', 'event_type'], name='sharing_sha_video_c_4253f7_idx'),
        ),
        migrations.AddIndex(
            model_name='shareactivity',
            index=models.Index(fields=['doctor_id', 'shared_at'], name='sharing_sha_doctor__d4d086_idx'),
        ),
        migrations.AddIndex(
            model_name='shareactivity',
            index=models.Index(fields=['shared_item_type', 'shared_item_code'], name='sharing_sha_shared__51353f_idx'),
        ),
    ]
